### ISSUE TITLE
Value input sidebar

### ISSUE THREAD

**Issue by Edds390** [Edds390/solarnetwork-aggregated-dashboard#25]
Users will want to see different values (i.e. different graph views for voltage, Watts, etc). We need an interface for selecting different value views.

**Comment by elisalter** [comment]
does this relate to the graph? which component is this @Edds390

**Comment by Edds390** [comment]
Yes it does relate to the graph; based on the value pressed it will update the graph. @elisalter Hasn't been implemented yet.
