### ISSUE TITLE
Able to enter a project that does not exist throwing an error

### ISSUE THREAD

**Issue by NathanHenderson** [Edds390/solarnetwork-aggregated-dashboard#43]
Issue Size: Small
The user can enter in a project name that does not exist into the search bar and then press enter to throw an error.
The application should check that the user has entered a valid project name, and if they have not give a warning.
![error](https://user-images.githubusercontent.com/6946056/38170162-d452b0aa-35d1-11e8-8f68-4fe6cabf738f.PNG)

**Comment by elisalter** [comment]
@NathanHenderson how can I reproduce this error? 

Update: resolved
